### ISSUE TITLE
Pictures are not loading

### ISSUE THREAD

**Issue by valek-web** [br4ndy-code/br4ndy-code.github.io#1]
If index.html is not opened through a live server, then the images are not loaded either
![_C__Users_Valek_Downloads_br4ndy-code github io-main_index html](https://user-images.githubusercontent.com/59340767/221003824-785363b6-bba1-4cf5-9a10-2db289245894.png)

**Comment by br4ndy-code** [comment]
Yeah, I used an absolute path for my images. I fixed it 
Thanks for contributing
